"""
Theme provider — switching logic and NiceGUI integration.
Delegates CSS generation to app.theme module for backward compatibility.
"""
from theme import (
    append_hyperos_css as _inject_hyperos,
    get_global_css as _global_css,
    get_theme as _get,
    set_theme as _set,
    toggle_theme as _toggle,
    is_dark as _is_dark,
)
from theme.tokens import (
    PRIMARY, PRIMARY_DARK, PRIMARY_LIGHT, ACCENT_GOLD,
    BACKGROUND, SURFACE, BORDER, TEXT_PRIMARY, TEXT_SECONDARY,
    SUCCESS, WARNING, ERROR, INFO,
    DARK_BACKGROUND, DARK_SURFACE, DARK_BORDER,
    DARK_TEXT_PRIMARY, DARK_TEXT_SECONDARY,
    SHADOW_SM, SHADOW_MD, SHADOW_LG,
    RADIUS_INPUT, RADIUS_CARD, RADIUS_FULL,
    TEXT_H1, TEXT_H2, TEXT_H3, TEXT_BODY, TEXT_BODY_SM,
    GLASS_BG, GLASS_BG_DARK, GLASS_BLUR,
)


def apply_theme():
    """Apply theme to the current page. Called at the top of every @ui.page handler."""
    _inject_hyperos()
    # Legacy CSS is still generated by theme.py's append_hyperos_css


def get_theme() -> str:
    """Return current theme: 'light' or 'dark'."""
    return _get()


def toggle_theme():
    """Toggle between light and dark mode."""
    _toggle()


def is_dark() -> bool:
    """True if dark mode is active."""
    return _is_dark()


__all__ = [
    "apply_theme", "get_theme", "toggle_theme", "is_dark",
]
