"""Executable design-token contract shared by NiceGUI and Cloudflare checks.

The source JSON is intentionally framework-neutral. NiceGUI consumes the
generated CSS and Quasar bridge, while the Cloudflare Worker keeps its current
runtime boundary and is checked against the generated Worker contract.
"""

from __future__ import annotations

from functools import lru_cache
import json
from pathlib import Path
import re
from typing import Any, Mapping

from nicegui_app.config import PROJECT_ROOT


SOURCE_PATH = PROJECT_ROOT / "design_system" / "tokens.v1.json"
NICEGUI_CSS_PATH = (
    PROJECT_ROOT / "nicegui_app" / "assets" / "css" / "sing-yin-tokens-v1.css"
)
WORKER_CONTRACT_PATH = (
    PROJECT_ROOT / "cloudflare" / "roster_viewer" / "design-tokens-v1.generated.json"
)
THEME_MARKUP_PATH = PROJECT_ROOT / "nicegui_app" / "ui" / "theme_markup.py"
WORKER_RUNTIME_PATH = PROJECT_ROOT / "cloudflare" / "roster_viewer" / "worker.js"

_REFERENCE = re.compile(r"^\{(?P<path>[A-Za-z0-9_.-]+)\}$")
_CSS_VARIABLE = re.compile(r"(?P<name>--[A-Za-z0-9_-]+)\s*:\s*(?P<value>[^;]+);")


class DesignTokenContractError(ValueError):
    """Raised when the machine-readable design contract is invalid or stale."""


@lru_cache(maxsize=1)
def load_design_token_contract() -> dict[str, Any]:
    """Load and validate the versioned token source once per process."""

    contract = json.loads(SOURCE_PATH.read_text(encoding="utf-8"))
    if contract.get("contractVersion") != "1.2.0":
        raise DesignTokenContractError("Unsupported design-token contract version")
    if contract.get("layerOrder") != ["primitive", "semantic", "component"]:
        raise DesignTokenContractError(
            "Token layer order must remain primitive -> semantic -> component"
        )
    for platform in ("nicegui", "worker"):
        if platform not in contract.get("platforms", {}):
            raise DesignTokenContractError(f"Missing platform token contract: {platform}")
        for mode in ("light", "dark"):
            resolved_token_map(contract, platform, mode)
    for mode in ("light", "dark"):
        quasar_palette(contract, mode)
    return contract


def _path_value(root: Mapping[str, Any], path: str) -> Any:
    value: Any = root
    for segment in path.split("."):
        if not isinstance(value, Mapping) or segment not in value:
            raise DesignTokenContractError(f"Unknown token reference: {path}")
        value = value[segment]
    return value


def _resolve_value(
    root: Mapping[str, Any],
    value: Any,
    *,
    chain: tuple[str, ...] = (),
) -> str:
    if not isinstance(value, str):
        raise DesignTokenContractError(f"Token value must be a string, got {value!r}")
    match = _REFERENCE.fullmatch(value)
    if match is None:
        return value
    path = match.group("path")
    if path in chain:
        raise DesignTokenContractError(
            f"Circular token reference: {' -> '.join((*chain, path))}"
        )
    return _resolve_value(root, _path_value(root, path), chain=(*chain, path))


def resolved_token_map(
    contract: Mapping[str, Any],
    platform: str,
    mode: str,
) -> dict[str, str]:
    """Merge semantic and component layers for one platform and theme."""

    platform_contract = contract["platforms"][platform]
    result: dict[str, str] = {}
    for layer in ("semantic", "component"):
        values = platform_contract["layers"][layer].get(mode, {})
        for name, raw_value in values.items():
            if not name.startswith("--"):
                raise DesignTokenContractError(
                    f"{platform}.{mode}.{layer} token must start with --: {name}"
                )
            if name in result:
                raise DesignTokenContractError(
                    f"Duplicate token ownership for {platform}.{mode}.{name}"
                )
            result[name] = _resolve_value(contract, raw_value)
    return result


def quasar_palette(
    contract: Mapping[str, Any] | None = None,
    mode: str = "light",
) -> dict[str, str]:
    """Return the framework-fill bridge from the same canonical source."""

    active_contract = contract or load_design_token_contract()
    palette = active_contract["bridges"]["quasar"][mode]
    return {
        name: _resolve_value(active_contract, raw_value)
        for name, raw_value in palette.items()
    }


def render_nicegui_css(contract: Mapping[str, Any] | None = None) -> str:
    """Render the deterministic NiceGUI CSS-variable layer."""

    active_contract = contract or load_design_token_contract()
    platform = active_contract["platforms"]["nicegui"]
    lines = [
        "/*",
        " * Generated from design_system/tokens.v1.json.",
        " * Do not edit this file directly; run scripts/generate_design_system_tokens.py.",
        " */",
        "@layer sy.tokens {",
    ]
    for mode, selector in (
        ("light", platform["selectors"]["light"]),
        ("dark", platform["selectors"]["dark"]),
    ):
        lines.append(f"{selector} {{")
        lines.append(
            f"  --sy-design-contract-version: {active_contract['contractVersion']};"
        )
        for name, value in resolved_token_map(active_contract, "nicegui", mode).items():
            lines.append(f"  {name}: {value};")
        # Keep Quasar's framework variables on the same selector as the
        # semantic theme tokens.  System-theme resolution happens in the
        # browser before the Python event round-trip, so a body--dark class
        # change must update both layers without requiring a page reload.
        for name, value in quasar_palette(active_contract, mode).items():
            css_name = name.replace("_", "-")
            lines.append(f"  --q-{css_name}: {value};")
        lines.append("}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_worker_contract(contract: Mapping[str, Any] | None = None) -> str:
    """Render the deterministic machine contract for Worker token validation."""

    active_contract = contract or load_design_token_contract()
    platform = active_contract["platforms"]["worker"]
    payload = {
        "contractVersion": active_contract["contractVersion"],
        "generatedFrom": "design_system/tokens.v1.json",
        "selectors": platform["selectors"],
        "themes": {
            mode: resolved_token_map(active_contract, "worker", mode)
            for mode in ("light", "dark")
        },
    }
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def expected_generated_files(
    contract: Mapping[str, Any] | None = None,
) -> dict[Path, str]:
    active_contract = contract or load_design_token_contract()
    return {
        NICEGUI_CSS_PATH: render_nicegui_css(active_contract),
        WORKER_CONTRACT_PATH: render_worker_contract(active_contract),
    }


def write_generated_files() -> None:
    """Regenerate both checked-in token artifacts."""

    for path, content in expected_generated_files().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


def generated_file_drift() -> list[str]:
    """Return deterministic drift descriptions without mutating the workspace."""

    drift: list[str] = []
    for path, expected in expected_generated_files().items():
        if not path.is_file():
            drift.append(f"missing generated file: {path.relative_to(PROJECT_ROOT)}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            drift.append(f"stale generated file: {path.relative_to(PROJECT_ROOT)}")
    return drift


def _extract_css_block(source: str, selector: str, *, start: int = 0) -> str:
    match = re.search(re.escape(selector) + r"\s*\{", source[start:])
    if match is None:
        raise DesignTokenContractError(f"Missing CSS selector: {selector}")
    body_start = start + match.end()
    cursor = body_start
    depth = 1
    while cursor < len(source) and depth:
        if source[cursor] == "{":
            depth += 1
        elif source[cursor] == "}":
            depth -= 1
        cursor += 1
    if depth:
        raise DesignTokenContractError(f"Unclosed CSS selector: {selector}")
    return source[body_start : cursor - 1]


def _css_variables(block: str) -> dict[str, str]:
    return {
        match.group("name"): match.group("value").strip()
        for match in _CSS_VARIABLE.finditer(block)
    }


def worker_runtime_drift(
    contract: Mapping[str, Any] | None = None,
) -> list[str]:
    """Compare the public gateway/viewer runtime with its generated contract."""

    active_contract = contract or load_design_token_contract()
    source = WORKER_RUNTIME_PATH.read_text(encoding="utf-8")
    viewer_start = source.index("const VIEWER_CSS")
    viewer_end = source.index("const VIEWER_JS", viewer_start)
    viewer_css = source[viewer_start:viewer_end]
    selectors = active_contract["platforms"]["worker"]["selectors"]
    expected = {
        "light": resolved_token_map(active_contract, "worker", "light"),
        "dark": resolved_token_map(active_contract, "worker", "dark"),
    }
    actual = {
        "light": _css_variables(_extract_css_block(viewer_css, selectors["light"])),
        "dark": _css_variables(_extract_css_block(viewer_css, selectors["dark"])),
        "autoDark": _css_variables(
            _extract_css_block(viewer_css, selectors["autoDark"])
        ),
    }
    drift: list[str] = []
    for mode in ("light", "dark"):
        if actual[mode] != expected[mode]:
            drift.append(f"Worker {mode} runtime tokens differ from contract")
    if actual["autoDark"] != expected["dark"]:
        drift.append("Worker automatic dark tokens differ from dark contract")
    return drift


def theme_integration_drift(
    contract: Mapping[str, Any] | None = None,
) -> list[str]:
    """Ensure the generated layer loads first and cannot be overridden silently."""

    active_contract = contract or load_design_token_contract()
    markup = THEME_MARKUP_PATH.read_text(encoding="utf-8")
    token_href = "/assets/css/sing-yin-tokens-v1.css"
    theme_href = "/assets/css/sing-yin-theme-v1.css"
    drift: list[str] = []
    if token_href not in markup:
        drift.append("NiceGUI head does not load the generated token CSS")
    elif theme_href not in markup or markup.index(token_href) > markup.index(theme_href):
        drift.append("NiceGUI token CSS must load before the compatibility theme")

    managed_tokens = set(resolved_token_map(active_contract, "nicegui", "light"))
    managed_tokens.update(resolved_token_map(active_contract, "nicegui", "dark"))
    css_root = NICEGUI_CSS_PATH.parent
    for css_path in sorted(css_root.glob("*.css")):
        if css_path == NICEGUI_CSS_PATH:
            continue
        declarations = {
            match.group("name")
            for match in _CSS_VARIABLE.finditer(css_path.read_text(encoding="utf-8"))
        }
        redeclared = managed_tokens.intersection(declarations)
        if redeclared:
            drift.append(
                f"{css_path.name} redeclares managed tokens: "
                + ", ".join(sorted(redeclared))
            )
    return drift


def validate_design_token_contract() -> list[str]:
    """Return every contract/generation/runtime integration problem."""

    contract = load_design_token_contract()
    return [
        *generated_file_drift(),
        *theme_integration_drift(contract),
        *worker_runtime_drift(contract),
    ]
