"""Generate the Cloudflare-safe embedded Service Weave browser asset."""

from __future__ import annotations

import argparse
import base64
import hashlib
from io import BytesIO
import json
from pathlib import Path

from PIL import Image


PROJECT_ROOT = Path(__file__).resolve().parents[1]
IDENTITY_SOURCE = PROJECT_ROOT / "design_system" / "product-identity.v1.json"
IDENTITY = json.loads(IDENTITY_SOURCE.read_text(encoding="utf-8"))
PRODUCT_VARIANTS = {
    variant["key"]: variant
    for variant in IDENTITY["productMarkVariants"]
}
DELIVERY = IDENTITY["delivery"]


def _variant_path(key: str) -> Path:
    return PROJECT_ROOT / PRODUCT_VARIANTS[key]["relativePath"]


SOURCE = _variant_path(DELIVERY["faviconVariant"])
LIGHT_MARK = _variant_path("mark-light")
WHITE_MARK = _variant_path("mark-white")
OUTPUT = PROJECT_ROOT / DELIVERY["workerGeneratedModule"]
WORKER_PUBLIC_ASSET_DIR = PROJECT_ROOT / "cloudflare" / "roster_viewer" / "public" / "assets"
WORKER_LANDING_ASSETS = {
    "service-weave-mark-light-v1.png": _variant_path(
        DELIVERY["workerLandingLightVariant"]
    ),
    "service-weave-mark-dark-v1.png": _variant_path(
        DELIVERY["workerLandingDarkVariant"]
    ),
}


def render_module(payload: bytes) -> str:
    encoded = base64.b64encode(payload).decode("ascii")
    chunks = [encoded[index : index + 120] for index in range(0, len(encoded), 120)]
    chunk_lines = "\n".join(f"  '{chunk}'," for chunk in chunks)
    digest = hashlib.sha256(payload).hexdigest()
    return (
        "// Generated by scripts/generate_service_weave_delivery.py; do not edit manually.\n"
        "export const SERVICE_WEAVE_FAVICON_BASE64 = [\n"
        f"{chunk_lines}\n"
        "].join('');\n"
        f"export const SERVICE_WEAVE_FAVICON_SHA256 = '{digest}';\n"
        f"export const SERVICE_WEAVE_FAVICON_BYTE_LENGTH = {len(payload)};\n"
    )


def render_white_mark() -> bytes:
    """Derive a literal-white mark while preserving the approved alpha geometry."""

    with Image.open(LIGHT_MARK) as source:
        rgba = source.convert("RGBA")
        white = Image.new("RGBA", rgba.size, (255, 255, 255, 0))
        white.putalpha(rgba.getchannel("A"))
        output = BytesIO()
        white.save(output, format="PNG", optimize=True, compress_level=9)
        return output.getvalue()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated module is stale.",
    )
    args = parser.parse_args()
    expected_white_mark = render_white_mark()
    expected = render_module(SOURCE.read_bytes())
    if args.check:
        if not WHITE_MARK.is_file() or WHITE_MARK.read_bytes() != expected_white_mark:
            raise SystemExit(
                "Service Weave white mark is stale; regenerate it from the approved geometry."
            )
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("Service Weave Cloudflare delivery module is stale; regenerate it.")
        for filename, source in WORKER_LANDING_ASSETS.items():
            delivered = WORKER_PUBLIC_ASSET_DIR / filename
            if not delivered.is_file() or delivered.read_bytes() != source.read_bytes():
                raise SystemExit(
                    f"Service Weave Cloudflare landing asset is stale: {filename}"
                )
        return 0
    WHITE_MARK.write_bytes(expected_white_mark)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    WORKER_PUBLIC_ASSET_DIR.mkdir(parents=True, exist_ok=True)
    for filename, source in WORKER_LANDING_ASSETS.items():
        (WORKER_PUBLIC_ASSET_DIR / filename).write_bytes(source.read_bytes())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
