import pathlib, py_compile
p = pathlib.Path(r"D:\code_v2\app\pages\prefects.py")
c = p.read_text("utf-8")
c = c.replace(".classes(\"w-full rounded-[20px] shadow-sm p-6\")", ".classes(\"w-full rounded-[20px] shadow-sm p-6 dark:bg-slate-800\")")
c = c.replace(".classes(\"w-full rounded-[20px] shadow-sm p-12 text-center\")", ".classes(\"w-full rounded-[20px] shadow-sm p-12 text-center dark:bg-slate-800\")")
c = c.replace(".classes(\"rounded-xl p-6 max-w-2xl max-h-[80vh] overflow-y-auto\")", ".classes(\"rounded-xl p-6 max-w-2xl max-h-[80vh] overflow-y-auto dark:bg-slate-800\")")
c = c.replace(".classes(\"rounded-xl p-6 max-w-lg w-full\")", ".classes(\"rounded-xl p-6 max-w-lg w-full dark:bg-slate-800\")")
p.write_text(c, "utf-8")
print(f"prefects.py dark: {c.count(chr(100)+chr(97)+chr(114)+chr(107)+chr(58))}")
py_compile.compile(str(p), doraise=True)
print("prefects.py OK")

p2 = pathlib.Path(r"D:\code_v2\app\pages\roster.py")
c2 = p2.read_text("utf-8")
c2 = c2.replace(".classes(\"w-full rounded-[20px] shadow-sm p-6\")", ".classes(\"w-full rounded-[20px] shadow-sm p-6 dark:bg-slate-800\")")
c2 = c2.replace(".classes(\"w-full rounded-lg overflow-hidden\")", ".classes(\"w-full rounded-lg overflow-hidden dark:bg-slate-800\")")
p2.write_text(c2, "utf-8")
print(f"roster.py dark: {c2.count(chr(100)+chr(97)+chr(114)+chr(107)+chr(58))}")
py_compile.compile(str(p2), doraise=True)
print("roster.py OK")
